name: CI-CD
on:
    workflow_dispatch:
jobs:
  ci:
    name: "CI - Continuos Integration"
    runs-on: ubuntu-latest
    steps:
        - name: "Obtendo arquivos do projeto"
          uses: actions/checkout@v4

        - name: "Autenticacao no Docker"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: "Build/Push da imagem Docker"
          uses: docker/build-push-action@v5
          with:
            context: ./src
            file: ./src/Dockerfile
            push: true
            tags: |
                fspelling/primeira-pipeline:v${{ github.run_number }}
                fspelling/primeira-pipeline:latest    
  cd-hml:
    name: "CD (HML) - Continuos Delivery/Deploy"
    needs: ["ci"]
    uses: fspelling/primeira-pipeline-cicd/.github/workflows/pipe-cd.yml@main
    with:
        manifest: ./k8s/deployment.yaml
        image: fspelling/primeira-pipeline:v${{ github.run_number }}
        environment: HML
    secrets: inherit
  testes-hml:
    name: "Testes no ambiente hml"
    needs: ["cd-hml"]
    runs-on: ubuntu-latest
    steps:
        - name: "Testes HML"
          run: echo "testes"
  cd-prd:
    name: "CD (PRD) - Continuos Delivery/Deploy"
    needs: ["testes-hml"]
    uses: fspelling/primeira-pipeline-cicd/.github/workflows/pipe-cd.yml@main
    with:
        manifest: ./k8s/deployment.yaml
        image: fspelling/primeira-pipeline:v${{ github.run_number }}
        environment: PRD
    secrets: inherit
