name: pipeline-teste
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "Variavel declarado no workflow"
jobs:
  job-test:
    name: "Iniciando execcao do Job (job-test)"
    runs-on: ubuntu-latest
    steps:
      - name: "step 1"
        run: echo "$ENV_WORKFLOW"
