name: pipeline-teste
env:
  ENV_WORKFLOW: "Variavel declarado no workflow"
on:
  workflow_dispatch:
jobs:
  job-test:
    name: "Iniciando execcao do Job (job-test)"
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Variavel declarado no job"
    steps:
      - name: "step 1"
        env:
          ENV_STEP: "Variavel declarado no step 1" # <--
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_STEP"
      - name: "step 2"
        run: echo "$ENV_JOB"
