name: pipeline-teste
on:
  workflow_dispatch:
jobs:
  job-test:
    name: "Iniciando execcao do Job (job-test)"
    runs-on: ubuntu-latest
    steps:
      - name: "step 1"
        run: echo "valor fixo"
